name: "CI"
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout this repository
      uses: actions/checkout@v2
    - name: Cache for arduino-ci
      uses: actions/cache@v3
      with:
        path: |
          ~/.arduino15
        key: ${{ runner.os }}-arduino
    - name: Install nix
      uses: cachix/install-nix-action@v12
    - name: Disable Nix sandboxing
      run: echo "sandbox = false" | sudo tee -a /etc/nix/nix.conf
    - run: nix-shell -I nixpkgs=channel:nixpkgs-unstable -p arduino-ci --run "arduino-ci"
