name: "CI"
on:
  pull_request:
  push:
jobs:
  ci:
    runs-on: ubuntu
    steps:
    - name: Checkout this repository
      uses: actions/checkout
    - name: Cache for arduino-ci
      uses: actions/cache
      with:
        path: |
          ~/.arduino15
        key: ${{ runner.os }}-arduino
    - name: Install nix
      uses: cachix/install-nix-action
    - run: nix-shell -I nixpkgs=channel:nixpkgs-unstable -p arduino-ci --run "arduino-ci"
